apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  credentials: eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJBRE1JTl9QQVNTIiwgImRvbWFpbiI6ICJkZWZhdWx0In0= 


