apiVersion: iot.s4t.crossplane.io/v1alpha1
kind: Device
metadata:
  name: my-device
  labels:
    environment: production
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: "My IoT Device"
    uuid: "" 
    type: "server"
    status: 
    location:
      - latitude: "37.7749"
        longitude: "-122.4194"
        altitude: "30"
        updated_at: []
    lr_version: 
    wstun_ip: 
    agent: 
    code: 
    session: 
    plugins:
    services:


